# Generated by Django 3.0.4 on 2020-03-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_caption_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Caption',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
