# Generated by Django 3.0.4 on 2020-03-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20200309_0156'),
    ]

    operations = [
    ]
